### ISSUE TITLE
Can u publish skill assessment solutions?

### ISSUE THREAD

**Issue by johnfelipe** [qiaohuang/DataCamp#1]

**Comment by qiaohuang** [comment]
You mean "Signal Assessments"? Sorry it's not public.

**Comment by johnfelipe** [comment]
No signal
I mean skill assessment, questions and answers, tests...

**Comment by qiaohuang** [comment]
Sorry, I'm afraid I can't export the data for uploading to GitHub. You can
get help from others. By the way, assessment is something you need to do
yourself to make sense.

**Comment by qiaohuang** [comment]
Sorry, I'm afraid I can't export the data for uploading to GitHub. You can
get help from others. By the way, assessment is something you need to do
yourself to make sense.

**Comment by qiaohuang** [comment]
You mean "Signal Assessments"? Sorry, it's not public.
